---
version: '3'

services:
  segmer:
    container_name: segmer
    build:
      context: .
      dockerfile: Dockerfile
    image: dceoy/segmer:latest
    user: ${UID}:${GID}
    userns_mode: host
    volumes:
      - ${PWD}:/wd
    working_dir: /wd
    entrypoint:
      - /usr/local/bin/segmer
